### ISSUE TITLE
Running get_swc.py on PowerShell, Windows 10

### ISSUE THREAD

**Issue by jarosado0911** [NeuroBox3D/neuromorpho#2]
Hi, when I execute: python get_swc.py --filter "cell_type=pyramidal" --neurons 10 --search "brain_region:neocortex" --filter "archive=Allen Cell Types"

I get the following error message: 
Traceback (most recent call last):
  File "get_swc.py", line 33, in <module>
    fileName = get_swc_by_filter_rule_for_search_term(args.filters, args.search, args.neurons, -1)
  File "C:\Users\jaros_000\Desktop\neuromorpho-master\rest_wrapper\rest_wrapper.py", line 84, in get_swc_by_filter_rule_for_search_term
    if (not check_api_health()): return
  File "C:\Users\jaros_000\Desktop\neuromorpho-master\rest_wrapper\rest_wrapper.py", line 45, in check_api_health
    if (json.loads(response.read())['status'].decode('utf-8') != "UP"):
  File "C:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

What am I missing? I also tried to execute the other example commands and I keep getting the same error. Thanks :)

**Comment by stephanmg** [comment]
Thank you for reporting this, the commit reference above should fix your problem.

Let me know if the error persists and feel free to re-open this issue.

**Comment by jarosado0911** [comment]
Thank you @stephanmg it appears to work now and it downloads the geometry. Minor note: now when it completes it says: 
None

Is it meant to say 'Done' ?

**Comment by stephanmg** [comment]
> Thank you @stephanmg it appears to work now and it downloads the geometry. Minor note: now when it completes it says:
> None
> 
> Is it meant to say 'Done' ?

Shouldn't say anything, this was a remnant from previous code refactorings.
